dist: trusty
sudo: required
language:
  - cpp
  - pyhton
compiler:
  - gcc
python:
  - "2.7"

sudo: true
cache:
  directories:
  - "~/.platformio"

install:
- pip install --user platformio
- mkdir -p ~/.local/bin
- wget -O ~/.local/bin/cpplint "$CPP_LINT_URL" && chmod 755 ~/.local/bin/cpplint

script:
- PATH=~/.local/bin:$PATH
- make lint
- make ci

env:
  global:
  - CPP_LINT_URL=https://raw.githubusercontent.com/google/styleguide/gh-pages/cpplint/cpplint.py
